const polkadotApi = require('@polkadot/api');
const polkadotUtilCrypto = require('@polkadot/util-crypto');

const { Keyring } = polkadotApi
const { cryptoWaitReady } = polkadotUtilCrypto

// Secret key coming from PQS env variables and previously generated by subkey https://www.substrate.io/kb/integrate/subkey)
const createKeyPair = async (uri) => {
  await cryptoWaitReady();
  const keyring = new Keyring({ type: 'sr25519' });
  return keyring.addFromUri(uri);
}

module.exports = createKeyPair
